### ISSUE TITLE
add column on tb_cast (file_loc, action_type)

### ISSUE THREAD

**Issue by PETER-ITPE** [noenemy/reinvent2018-got-talent#13]
column add 
영화 이미지와 주요 감정 저장을 위한 컬럼 추가
 ex) 어벤져스 헐크 이미지, Action_type ANGRY

 1) Movie screen shot (image - s3 url)
 2) Action_type (HAPPY | SAD | ANGRY | CONFUSED | DISGUSTED | SURPRISED | CALM | UNKNOWN) not mandatory

  file_loc varchar(2083) DEFAULT NULL
  action_type varchar(100) DEFAULT NULL

**Comment by noenemy** [comment]
Resolved by modifying Casting class as below.

    public class Casting
    {
        [Key]
        public int cast_id { get; set; }
        public string title { get; set; }
        public string actor { get; set; }
        public string gender { get; set; } // Male, Female
        public string grade { get; set; } // A, B, C ...
        **public string file_loc { get; set; }
        public string action_type { get; set; }**
    }
