### ISSUE TITLE
Research Amazon Cognito integration for gaming users

### ISSUE THREAD

**Issue by noenemy** [noenemy/reinvent2018-got-talent#3]
I think we need to research whether Amazon Cognito integration is required for gaming users.

- [x] Initial research
- [ ] Discussion with soonkeun

**Comment by liks79** [comment]
Hello, all.

If we need to call AWS API at the WEB front-end, we can use identity-pool of AWS Cognito.
However, if AWS API call occurred at server-side only than IAM Role is better choice I think.

Please schedule a meeting about that.

Thanks a lot.

**Comment by noenemy** [comment]
As we discussed the issue offline, I agree with liks79's opinion.
To have more simple architecture, let's use IAM role on instance level instead of Cognito services.

Closing.
