### ISSUE TITLE
Architecture design for real-time leaderboard feature

### ISSUE THREAD

**Issue by noenemy** [noenemy/reinvent2018-got-talent#4]
I think we need architecture design for real-time leaderboard.
Currently, ranking API accesses database directory to get ranking result. Do we have any other enhanced architecture to do this?

e.g. ElastiCache or streaming service, ranking evaluation logic and etc...

**Comment by liks79** [comment]
I have an idea about that.
We can use Redis(Elasticache) pub/sub feature with SSE(ServerSideEvent) at front-end.
How about this?

**Comment by liks79** [comment]
Here is reference implementation in my repo.

- https://github.com/liks79/sse-redis-pubsub
